### ISSUE TITLE
生成代码格式不对

### ISSUE THREAD

**Issue by ZeroKill1024** [UpUpLiu/Entitas-lua#1]
你好，我clone下来后直接运行测试，运行正常；但是按照说明，我仅仅重新生成了一次代码，运行测试报错：
lua: error loading module 'GenerateEcsCore' from file './GenerateEcsCore.lua':
	./GenerateEcsCore.lua:1: 'end' expected near 'function'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	./test/test_entity_system.lua:4: in main chunk
	[C]: in function 'require'
	test_runtime.lua:157: in main chunk
	[C]: in ?
查看生成的GenerateEcsCore.lua发现格式和原来的不一致，所有代码在一行，且空格也不对：
local t_remove = table.removelocal Bag = Entitas.Baglocal Entity = Entitas.Entitylocal Context = Entitas.Contextlocal function com_tostring(obj) ...

**Comment by UpUpLiu** [comment]
正在进行修改,  准备用lua做配置文件  大概2天后会上传

**Comment by UpUpLiu** [comment]
因为之前的项目被暂时搁置 所以开发计划搁浅了一段时间.. 现在正在重新开发并维护
